[package]
authors = ["Rishabh Chawla <rishabh31121999@gmail.com>"]
name = "unique_identifier"
version = "0.1.0"
edition = "2021"

[dependencies]
swc_core = { version = "16.0.0", features = [
  "ecma_plugin_transform",
  "__parser",
] }
